var locale = d3.timeFormatLocale({
  "dateTime": "%a %e %b %Y %X",
  // "date": "%d-%m-%Y",
  "date": "%Y-%m",
  "time": "%Hh%M",
  "periods": ["am", "pm"],
  "days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  "shortDays": ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  "shortMonths": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
});

var timeFormat = function(date) {
  return (
    // d3.timeDay(date) < date ? locale.format("%Hh") :
    // d3.timeMonth(date) < date ? locale.format("%m") :
    d3.timeYear(date) < date ? locale.format("%b %Y") :
    d3.timeFormat("%Y")
  )(date);
};

// var data = createRandomData(600,[1000,1000000]);

var data2 = [{
    "date": new Date('2004-01'),
    "Iron Man": 2,
    "Hulk": 10,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-02'),
    "Iron Man": 2,
    "Hulk": 9,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-03'),
    "Iron Man": 2,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-04'),
    "Iron Man": 2,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-05'),
    "Iron Man": 3,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-06'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 8,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-07'),
    "Iron Man": 3,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 19,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-08'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-09'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-10'),
    "Iron Man": 3,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-11'),
    "Iron Man": 2,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2004-12'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-01'),
    "Iron Man": 2,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-02'),
    "Iron Man": 2,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-03'),
    "Iron Man": 2,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-04'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-05'),
    "Iron Man": 3,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-06'),
    "Iron Man": 3,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-07'),
    "Iron Man": 3,
    "Hulk": 9,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-08'),
    "Iron Man": 3,
    "Hulk": 10,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-09'),
    "Iron Man": 2,
    "Hulk": 10,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-10'),
    "Iron Man": 3,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-11'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2005-12'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-01'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-02'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-03'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-04'),
    "Iron Man": 2,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-05'),
    "Iron Man": 3,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-06'),
    "Iron Man": 3,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-07'),
    "Iron Man": 4,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-08'),
    "Iron Man": 3,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-09'),
    "Iron Man": 3,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-10'),
    "Iron Man": 4,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-11'),
    "Iron Man": 3,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2006-12'),
    "Iron Man": 3,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-01'),
    "Iron Man": 5,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-02'),
    "Iron Man": 3,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-03'),
    "Iron Man": 3,
    "Hulk": 6,
    "Thor": 5,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2007-04'),
    "Iron Man": 4,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 10,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-05'),
    "Iron Man": 4,
    "Hulk": 7,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 21,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-06'),
    "Iron Man": 4,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-07'),
    "Iron Man": 6,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-08'),
    "Iron Man": 6,
    "Hulk": 11,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 1,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-09'),
    "Iron Man": 10,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-10'),
    "Iron Man": 6,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-11'),
    "Iron Man": 5,
    "Hulk": 11,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2007-12'),
    "Iron Man": 6,
    "Hulk": 10,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-01'),
    "Iron Man": 6,
    "Hulk": 9,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-02'),
    "Iron Man": 8,
    "Hulk": 8,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-03'),
    "Iron Man": 10,
    "Hulk": 18,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-04'),
    "Iron Man": 24,
    "Hulk": 12,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-05'),
    "Iron Man": 77,
    "Hulk": 20,
    "Thor": 6,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-06'),
    "Iron Man": 25,
    "Hulk": 57,
    "Thor": 6,
    "Captain America": 3,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-07'),
    "Iron Man": 15,
    "Hulk": 27,
    "Thor": 5,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-08'),
    "Iron Man": 12,
    "Hulk": 16,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-09'),
    "Iron Man": 15,
    "Hulk": 15,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-10'),
    "Iron Man": 18,
    "Hulk": 18,
    "Thor": 6,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-11'),
    "Iron Man": 13,
    "Hulk": 15,
    "Thor": 5,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2008-12'),
    "Iron Man": 11,
    "Hulk": 14,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-01'),
    "Iron Man": 9,
    "Hulk": 13,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-02'),
    "Iron Man": 8,
    "Hulk": 12,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-03'),
    "Iron Man": 8,
    "Hulk": 11,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-04'),
    "Iron Man": 8,
    "Hulk": 12,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-05'),
    "Iron Man": 9,
    "Hulk": 12,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-06'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-07'),
    "Iron Man": 12,
    "Hulk": 11,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 0,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-08'),
    "Iron Man": 11,
    "Hulk": 12,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-09'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-10'),
    "Iron Man": 8,
    "Hulk": 11,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 3,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-11'),
    "Iron Man": 8,
    "Hulk": 11,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2009-12'),
    "Iron Man": 19,
    "Hulk": 11,
    "Thor": 5,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 0,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-01'),
    "Iron Man": 13,
    "Hulk": 12,
    "Thor": 6,
    "Captain America": 1,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-02'),
    "Iron Man": 12,
    "Hulk": 12,
    "Thor": 5,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-03'),
    "Iron Man": 17,
    "Hulk": 10,
    "Thor": 5,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-04'),
    "Iron Man": 38,
    "Hulk": 10,
    "Thor": 6,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-05'),
    "Iron Man": 83,
    "Hulk": 11,
    "Thor": 11,
    "Captain America": 3,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-06'),
    "Iron Man": 26,
    "Hulk": 10,
    "Thor": 7,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 0,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-07'),
    "Iron Man": 20,
    "Hulk": 11,
    "Thor": 11,
    "Captain America": 3,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-08'),
    "Iron Man": 18,
    "Hulk": 11,
    "Thor": 9,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-09'),
    "Iron Man": 21,
    "Hulk": 10,
    "Thor": 7,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-10'),
    "Iron Man": 20,
    "Hulk": 10,
    "Thor": 7,
    "Captain America": 3,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-11'),
    "Iron Man": 13,
    "Hulk": 10,
    "Thor": 6,
    "Captain America": 3,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2010-12'),
    "Iron Man": 12,
    "Hulk": 11,
    "Thor": 10,
    "Captain America": 2,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-01'),
    "Iron Man": 13,
    "Hulk": 11,
    "Thor": 8,
    "Captain America": 3,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-02'),
    "Iron Man": 10,
    "Hulk": 10,
    "Thor": 10,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-03'),
    "Iron Man": 9,
    "Hulk": 10,
    "Thor": 9,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-04'),
    "Iron Man": 10,
    "Hulk": 11,
    "Thor": 32,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-05'),
    "Iron Man": 10,
    "Hulk": 13,
    "Thor": 67,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-06'),
    "Iron Man": 9,
    "Hulk": 12,
    "Thor": 22,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-07'),
    "Iron Man": 12,
    "Hulk": 12,
    "Thor": 20,
    "Captain America": 28,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2011-08'),
    "Iron Man": 11,
    "Hulk": 12,
    "Thor": 20,
    "Captain America": 19,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2011-09'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 21,
    "Captain America": 9,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-10'),
    "Iron Man": 10,
    "Hulk": 12,
    "Thor": 16,
    "Captain America": 13,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-11'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 11,
    "Captain America": 8,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2011-12'),
    "Iron Man": 9,
    "Hulk": 13,
    "Thor": 10,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2012-01'),
    "Iron Man": 8,
    "Hulk": 13,
    "Thor": 10,
    "Captain America": 5,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2012-02'),
    "Iron Man": 8,
    "Hulk": 13,
    "Thor": 8,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2012-03'),
    "Iron Man": 9,
    "Hulk": 16,
    "Thor": 11,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 4,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2012-04'),
    "Iron Man": 14,
    "Hulk": 20,
    "Thor": 14,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2012-05'),
    "Iron Man": 27,
    "Hulk": 35,
    "Thor": 27,
    "Captain America": 13,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2012-06'),
    "Iron Man": 17,
    "Hulk": 25,
    "Thor": 18,
    "Captain America": 7,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 12,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2012-07'),
    "Iron Man": 18,
    "Hulk": 21,
    "Thor": 13,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 30,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2012-08'),
    "Iron Man": 15,
    "Hulk": 19,
    "Thor": 12,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 11,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2012-09'),
    "Iron Man": 15,
    "Hulk": 20,
    "Thor": 13,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 9,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2012-10'),
    "Iron Man": 27,
    "Hulk": 32,
    "Thor": 12,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 9,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2012-11'),
    "Iron Man": 18,
    "Hulk": 16,
    "Thor": 10,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 10,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2012-12'),
    "Iron Man": 18,
    "Hulk": 16,
    "Thor": 10,
    "Captain America": 4,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 9,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2013-01'),
    "Iron Man": 17,
    "Hulk": 15,
    "Thor": 10,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2013-02'),
    "Iron Man": 21,
    "Hulk": 14,
    "Thor": 10,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2013-03'),
    "Iron Man": 25,
    "Hulk": 15,
    "Thor": 9,
    "Captain America": 3,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2013-04'),
    "Iron Man": 64,
    "Hulk": 14,
    "Thor": 15,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2013-05'),
    "Iron Man": 100,
    "Hulk": 16,
    "Thor": 13,
    "Captain America": 5,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2013-06'),
    "Iron Man": 39,
    "Hulk": 19,
    "Thor": 11,
    "Captain America": 5,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2013-07'),
    "Iron Man": 29,
    "Hulk": 20,
    "Thor": 12,
    "Captain America": 5,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 8,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2013-08'),
    "Iron Man": 30,
    "Hulk": 17,
    "Thor": 15,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2013-09'),
    "Iron Man": 26,
    "Hulk": 14,
    "Thor": 14,
    "Captain America": 4,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2013-10'),
    "Iron Man": 20,
    "Hulk": 14,
    "Thor": 24,
    "Captain America": 7,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2013-11'),
    "Iron Man": 17,
    "Hulk": 15,
    "Thor": 70,
    "Captain America": 6,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2013-12'),
    "Iron Man": 18,
    "Hulk": 15,
    "Thor": 32,
    "Captain America": 5,
    "Star Lord": 0,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 8,
    "Black Panther": 1,
    "Captain Marvel": 0
  },
  {
    "date": new Date('2014-01'),
    "Iron Man": 17,
    "Hulk": 14,
    "Thor": 25,
    "Captain America": 5,
    "Star Lord": 0,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-02'),
    "Iron Man": 16,
    "Hulk": 15,
    "Thor": 31,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-03'),
    "Iron Man": 15,
    "Hulk": 16,
    "Thor": 23,
    "Captain America": 17,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 8,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-04'),
    "Iron Man": 17,
    "Hulk": 18,
    "Thor": 19,
    "Captain America": 47,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 21,
    "Black Panther": 1,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2014-05'),
    "Iron Man": 16,
    "Hulk": 16,
    "Thor": 14,
    "Captain America": 17,
    "Star Lord": 0,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 35,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-06'),
    "Iron Man": 13,
    "Hulk": 29,
    "Thor": 14,
    "Captain America": 11,
    "Star Lord": 0,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 13,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-07'),
    "Iron Man": 14,
    "Hulk": 24,
    "Thor": 16,
    "Captain America": 13,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 12,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-08'),
    "Iron Man": 14,
    "Hulk": 19,
    "Thor": 14,
    "Captain America": 17,
    "Star Lord": 3,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 15,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-09'),
    "Iron Man": 12,
    "Hulk": 14,
    "Thor": 12,
    "Captain America": 12,
    "Star Lord": 1,
    "Ant-Man": 0,
    "Doctor Strange": 0,
    "Spider-Man": 11,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-10'),
    "Iron Man": 14,
    "Hulk": 15,
    "Thor": 15,
    "Captain America": 10,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 1,
    "Spider-Man": 9,
    "Black Panther": 1,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2014-11'),
    "Iron Man": 12,
    "Hulk": 14,
    "Thor": 12,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2014-12'),
    "Iron Man": 12,
    "Hulk": 14,
    "Thor": 12,
    "Captain America": 7,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 8,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-01'),
    "Iron Man": 13,
    "Hulk": 15,
    "Thor": 12,
    "Captain America": 9,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 0,
    "Spider-Man": 8,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-02'),
    "Iron Man": 12,
    "Hulk": 15,
    "Thor": 11,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 8,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-03'),
    "Iron Man": 13,
    "Hulk": 17,
    "Thor": 11,
    "Captain America": 7,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-04'),
    "Iron Man": 18,
    "Hulk": 19,
    "Thor": 14,
    "Captain America": 10,
    "Star Lord": 1,
    "Ant-Man": 2,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-05'),
    "Iron Man": 23,
    "Hulk": 24,
    "Thor": 18,
    "Captain America": 15,
    "Star Lord": 1,
    "Ant-Man": 2,
    "Doctor Strange": 1,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2015-06'),
    "Iron Man": 15,
    "Hulk": 18,
    "Thor": 12,
    "Captain America": 9,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-07'),
    "Iron Man": 14,
    "Hulk": 26,
    "Thor": 12,
    "Captain America": 10,
    "Star Lord": 1,
    "Ant-Man": 22,
    "Doctor Strange": 0,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-08'),
    "Iron Man": 14,
    "Hulk": 18,
    "Thor": 11,
    "Captain America": 11,
    "Star Lord": 1,
    "Ant-Man": 11,
    "Doctor Strange": 1,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2015-09'),
    "Iron Man": 14,
    "Hulk": 17,
    "Thor": 11,
    "Captain America": 9,
    "Star Lord": 1,
    "Ant-Man": 5,
    "Doctor Strange": 0,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-10'),
    "Iron Man": 13,
    "Hulk": 16,
    "Thor": 12,
    "Captain America": 9,
    "Star Lord": 1,
    "Ant-Man": 4,
    "Doctor Strange": 0,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-11'),
    "Iron Man": 12,
    "Hulk": 15,
    "Thor": 11,
    "Captain America": 12,
    "Star Lord": 1,
    "Ant-Man": 7,
    "Doctor Strange": 1,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2015-12'),
    "Iron Man": 12,
    "Hulk": 15,
    "Thor": 11,
    "Captain America": 11,
    "Star Lord": 1,
    "Ant-Man": 7,
    "Doctor Strange": 1,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2016-01'),
    "Iron Man": 12,
    "Hulk": 15,
    "Thor": 11,
    "Captain America": 10,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 1,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2016-02'),
    "Iron Man": 12,
    "Hulk": 15,
    "Thor": 11,
    "Captain America": 12,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 1,
    "Spider-Man": 6,
    "Black Panther": 3,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2016-03'),
    "Iron Man": 13,
    "Hulk": 25,
    "Thor": 11,
    "Captain America": 22,
    "Star Lord": 0,
    "Ant-Man": 3,
    "Doctor Strange": 1,
    "Spider-Man": 7,
    "Black Panther": 2,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2016-04'),
    "Iron Man": 16,
    "Hulk": 15,
    "Thor": 12,
    "Captain America": 35,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 3,
    "Spider-Man": 7,
    "Black Panther": 3,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2016-05'),
    "Iron Man": 20,
    "Hulk": 16,
    "Thor": 15,
    "Captain America": 73,
    "Star Lord": 1,
    "Ant-Man": 4,
    "Doctor Strange": 1,
    "Spider-Man": 8,
    "Black Panther": 5,
    "Captain Marvel": 3
  },
  {
    "date": new Date('2016-06'),
    "Iron Man": 14,
    "Hulk": 16,
    "Thor": 11,
    "Captain America": 19,
    "Star Lord": 0,
    "Ant-Man": 2,
    "Doctor Strange": 1,
    "Spider-Man": 7,
    "Black Panther": 2,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2016-07'),
    "Iron Man": 12,
    "Hulk": 15,
    "Thor": 12,
    "Captain America": 12,
    "Star Lord": 0,
    "Ant-Man": 2,
    "Doctor Strange": 1,
    "Spider-Man": 7,
    "Black Panther": 2,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2016-08'),
    "Iron Man": 10,
    "Hulk": 12,
    "Thor": 11,
    "Captain America": 11,
    "Star Lord": 0,
    "Ant-Man": 1,
    "Doctor Strange": 1,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2016-09'),
    "Iron Man": 10,
    "Hulk": 12,
    "Thor": 10,
    "Captain America": 13,
    "Star Lord": 0,
    "Ant-Man": 1,
    "Doctor Strange": 2,
    "Spider-Man": 5,
    "Black Panther": 2,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2016-10'),
    "Iron Man": 10,
    "Hulk": 13,
    "Thor": 10,
    "Captain America": 9,
    "Star Lord": 0,
    "Ant-Man": 1,
    "Doctor Strange": 9,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2016-11'),
    "Iron Man": 9,
    "Hulk": 13,
    "Thor": 11,
    "Captain America": 8,
    "Star Lord": 0,
    "Ant-Man": 1,
    "Doctor Strange": 24,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2016-12'),
    "Iron Man": 10,
    "Hulk": 13,
    "Thor": 10,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 8,
    "Spider-Man": 7,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-01'),
    "Iron Man": 9,
    "Hulk": 12,
    "Thor": 10,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 5,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-02'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 11,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 6,
    "Spider-Man": 5,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-03'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 12,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 4,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-04'),
    "Iron Man": 9,
    "Hulk": 12,
    "Thor": 20,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 2,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-05'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 12,
    "Captain America": 7,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 2,
    "Spider-Man": 6,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-06'),
    "Iron Man": 10,
    "Hulk": 11,
    "Thor": 12,
    "Captain America": 7,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 2,
    "Spider-Man": 10,
    "Black Panther": 4,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-07'),
    "Iron Man": 12,
    "Hulk": 12,
    "Thor": 17,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 2,
    "Doctor Strange": 2,
    "Spider-Man": 28,
    "Black Panther": 2,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2017-08'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 14,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 1,
    "Spider-Man": 10,
    "Black Panther": 2,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-09'),
    "Iron Man": 8,
    "Hulk": 10,
    "Thor": 14,
    "Captain America": 5,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 1,
    "Spider-Man": 8,
    "Black Panther": 1,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-10'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 39,
    "Captain America": 5,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 1,
    "Spider-Man": 9,
    "Black Panther": 3,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-11'),
    "Iron Man": 9,
    "Hulk": 12,
    "Thor": 84,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 2,
    "Spider-Man": 7,
    "Black Panther": 3,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2017-12'),
    "Iron Man": 10,
    "Hulk": 12,
    "Thor": 36,
    "Captain America": 7,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 2,
    "Spider-Man": 7,
    "Black Panther": 3,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2018-01'),
    "Iron Man": 8,
    "Hulk": 10,
    "Thor": 33,
    "Captain America": 5,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 1,
    "Spider-Man": 5,
    "Black Panther": 10,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2018-02'),
    "Iron Man": 10,
    "Hulk": 11,
    "Thor": 32,
    "Captain America": 7,
    "Star Lord": 1,
    "Ant-Man": 2,
    "Doctor Strange": 2,
    "Spider-Man": 6,
    "Black Panther": 100,
    "Captain Marvel": 1
  },
  {
    "date": new Date('2018-03'),
    "Iron Man": 11,
    "Hulk": 12,
    "Thor": 30,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 2,
    "Doctor Strange": 2,
    "Spider-Man": 6,
    "Black Panther": 47,
    "Captain Marvel": 2
  },
  {
    "date": new Date('2018-04'),
    "Iron Man": 14,
    "Hulk": 14,
    "Thor": 28,
    "Captain America": 11,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 3,
    "Spider-Man": 7,
    "Black Panther": 26,
    "Captain Marvel": 15
  },
  {
    "date": new Date('2018-05'),
    "Iron Man": 19,
    "Hulk": 17,
    "Thor": 37,
    "Captain America": 14,
    "Star Lord": 2,
    "Ant-Man": 5,
    "Doctor Strange": 5,
    "Spider-Man": 9,
    "Black Panther": 30,
    "Captain Marvel": 19
  },
  {
    "date": new Date('2018-06'),
    "Iron Man": 12,
    "Hulk": 13,
    "Thor": 24,
    "Captain America": 7,
    "Star Lord": 1,
    "Ant-Man": 5,
    "Doctor Strange": 2,
    "Spider-Man": 7,
    "Black Panther": 11,
    "Captain Marvel": 4
  },
  {
    "date": new Date('2018-07'),
    "Iron Man": 11,
    "Hulk": 12,
    "Thor": 19,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 22,
    "Doctor Strange": 2,
    "Spider-Man": 7,
    "Black Panther": 7,
    "Captain Marvel": 4
  },
  {
    "date": new Date('2018-08'),
    "Iron Man": 11,
    "Hulk": 12,
    "Thor": 19,
    "Captain America": 7,
    "Star Lord": 1,
    "Ant-Man": 8,
    "Doctor Strange": 2,
    "Spider-Man": 8,
    "Black Panther": 6,
    "Captain Marvel": 6
  },
  {
    "date": new Date('2018-09'),
    "Iron Man": 11,
    "Hulk": 11,
    "Thor": 17,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 5,
    "Doctor Strange": 1,
    "Spider-Man": 21,
    "Black Panther": 7,
    "Captain Marvel": 12
  },
  {
    "date": new Date('2018-10'),
    "Iron Man": 10,
    "Hulk": 11,
    "Thor": 15,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 6,
    "Doctor Strange": 1,
    "Spider-Man": 12,
    "Black Panther": 6,
    "Captain Marvel": 3
  },
  {
    "date": new Date('2018-11'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 14,
    "Captain America": 5,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 1,
    "Spider-Man": 10,
    "Black Panther": 5,
    "Captain Marvel": 3
  },
  {
    "date": new Date('2018-12'),
    "Iron Man": 10,
    "Hulk": 11,
    "Thor": 16,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 4,
    "Doctor Strange": 1,
    "Spider-Man": 18,
    "Black Panther": 5,
    "Captain Marvel": 9
  },
  {
    "date": new Date('2019-01'),
    "Iron Man": 9,
    "Hulk": 11,
    "Thor": 16,
    "Captain America": 5,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 1,
    "Spider-Man": 16,
    "Black Panther": 6,
    "Captain Marvel": 8
  },
  {
    "date": new Date('2019-02'),
    "Iron Man": 8,
    "Hulk": 11,
    "Thor": 13,
    "Captain America": 5,
    "Star Lord": 0,
    "Ant-Man": 3,
    "Doctor Strange": 1,
    "Spider-Man": 9,
    "Black Panther": 7,
    "Captain Marvel": 15
  },
  {
    "date": new Date('2019-03'),
    "Iron Man": 11,
    "Hulk": 12,
    "Thor": 17,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 3,
    "Doctor Strange": 1,
    "Spider-Man": 10,
    "Black Panther": 6,
    "Captain Marvel": 85
  },
  {
    "date": new Date('2019-04'),
    "Iron Man": 26,
    "Hulk": 17,
    "Thor": 30,
    "Captain America": 17,
    "Star Lord": 1,
    "Ant-Man": 5,
    "Doctor Strange": 2,
    "Spider-Man": 10,
    "Black Panther": 6,
    "Captain Marvel": 39
  },
  {
    "date": new Date('2019-05'),
    "Iron Man": 31,
    "Hulk": 17,
    "Thor": 36,
    "Captain America": 20,
    "Star Lord": 1,
    "Ant-Man": 4,
    "Doctor Strange": 3,
    "Spider-Man": 15,
    "Black Panther": 6,
    "Captain Marvel": 22
  },
  {
    "date": new Date('2019-06'),
    "Iron Man": 15,
    "Hulk": 12,
    "Thor": 19,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 2,
    "Doctor Strange": 1,
    "Spider-Man": 18,
    "Black Panther": 4,
    "Captain Marvel": 12
  },
  {
    "date": new Date('2019-07'),
    "Iron Man": 15,
    "Hulk": 11,
    "Thor": 20,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 2,
    "Doctor Strange": 2,
    "Spider-Man": 38,
    "Black Panther": 3,
    "Captain Marvel": 7
  },
  {
    "date": new Date('2019-08'),
    "Iron Man": 13,
    "Hulk": 12,
    "Thor": 17,
    "Captain America": 8,
    "Star Lord": 1,
    "Ant-Man": 2,
    "Doctor Strange": 1,
    "Spider-Man": 17,
    "Black Panther": 3,
    "Captain Marvel": 5
  },
  {
    "date": new Date('2019-09'),
    "Iron Man": 12,
    "Hulk": 10,
    "Thor": 14,
    "Captain America": 6,
    "Star Lord": 1,
    "Ant-Man": 1,
    "Doctor Strange": 1,
    "Spider-Man": 13,
    "Black Panther": 3,
    "Captain Marvel": 4
  }
];


// d3.json("chart2.json", function(data2) {
//     console.log(data);
// });


var chart = d3_timeseries()
  .addSerie(data2, {
    x: 'date',
    y: 'Iron Man'
  }, {
    interpolate: 'step-before'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Hulk'
  }, {
    interpolate: 'linear'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Thor'
  }, {
    interpolate: 'linear'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Captain America'
  }, {
    interpolate: 'linear'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Star Lord'
  }, {
    interpolate: 'linear'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Ant-Man'
  }, {
    interpolate: 'linear'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Doctor Strange'
  }, {
    interpolate: 'linear'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Spider-Man'
  }, {
    interpolate: 'linear'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Black Panther'
  }, {
    interpolate: 'linear'
  })
  .addSerie(null, {
    x: 'date',
    y: 'Captain Marvel'
  }, {
    interpolate: 'linear'
  })
  .xscale.tickFormat(timeFormat)
  .width(1200);

chart('#chart2');
